services:
  jupyterlab:
    container_name: docker-jupyterlab
    build: .
    restart: always
    entrypoint: >
      jupyter-lab --allow-root --ip=0.0.0.0 --port=8787 --no-browser --NotebookApp.token='' --notebook-dir=/workspace
    expose:
      - "8787"
    ports:
      - "127.0.0.1:8787:8787"
    volumes:
      - ./python/root_jupyter:/root/.jupyter
      - ./workspace:/workspace
